name: Pixel Grafik KG
favicon: null
layout_spectrum: 0.47721153357997537
typography_spectrum: 0.04759485018439591
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7846619416959584
  lightness: 0.9722404554486275
  saturation: 0.7593558127991855
  rhythmicContrast: 0.9400980507489294
purpose: []
